[package]
name = "cryptokit"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "0.4.3"
k256 = { version = "0.13.4", features = ["ecdsa", "sha256" ] }
rand_core = { version = "0.6.4", features = ["getrandom"] }
sha3 = "0.10.8"
